### ISSUE TITLE
Incubating Program: Follower Read With Applied Index

### ISSUE THREAD

**Issue by hicqu** [pingcap/community#86]
#### Summary

This RFC proposes a improvement about getting snapshot on followers, which is
if the read request carries an applied index, the peer can get snapshot locally
wihtout any commucation with its leader, if only it has applied to the given
index. It's useful to reduce latency if the cluster is deployed in multi
datacenters.

#### Motivation

For clusters deployed in multi datacenters, the system latency could mainly
depend on the network RTT between datacenters. For example, suppose PDs are
deployed in Beijing, and TiKVs are deployed in Beijing and Xian (for high
availability). If a client which is near to Xian wants to read a region, it
needs to get a transaction timestamp from PDs (in Beijing), and then sends
requests to TiKVs in Beijing or Xian. For the latter case, TiKVs in Xian will
send read index requests to their leaders (in Beijing) internally, which still
involves a RTT crossing datacenters.

So, If we can add some proxies in the major datacenter, and let it help TiDBs
in Xian to get transaction timestamp and applied indices of all target regions,
the read latency between multi datacenter will be reduced from 2 RTT to 1 RTT.

### Your RFC/Proposal?

https://github.com/tikv/rfcs/pull/32
https://github.com/tikv/rfcs/pull/33

### Tracking list
- [x] Article about the improvement (done)
#### TiKV tasks about follower read with applied index
- [x] RFC about follower read with applied index: https://github.com/tikv/rfcs/pull/32 (in review)
- [x] Support follower read with applied index in TiKV: https://github.com/tikv/tikv/pull/5972 (in review)
- [ ] DCProxy for GetTsAndAppliedIndex (unstarted)

#### TiDB tasks about follower read with applied index
- [x] Support location labels in TiDB: https://github.com/pingcap/tidb/pull/13296 (in review)
- [ ] Support getting ts from DCProxy in TiDB (unstarted)

#### Tasks about follower replication
- [x] RFC about follower replication: https://github.com/tikv/rfcs/pull/33 (in review)
- [x] follower replication implementation: https://github.com/tikv/raft-rs/pull/249 (in review)
- [ ] Introduce follower replication into TiKV (unstarted)

**Comment by winkyao** [comment]
LGTM

**Comment by qiuyesuifeng** [comment]
LGTM

**Comment by zz-jason** [comment]
LGTM

**Comment by tisonkun** [comment]
@hicqu @zz-jason is this feature released or stopped?

**Comment by hicqu** [comment]
Closed by https://github.com/pingcap/tidb/issues/21094.
